<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="iShop — the considered way to buy Apple.">
    <title>iShop — Apple, considered.</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
    <div id="loader" class="loader"><div class="loader-mark">●</div><span>iShop</span></div>
    <div class="cursor-glow"></div>
    <header class="site-header">
        <a class="brand" href="/" aria-label="iShop home"><span class="brand-mark">●</span><span>iShop</span></a>
        <nav class="main-nav" aria-label="Primary navigation"><a class="active" href="#shop">Shop</a><a href="#compare">Compare</a><a href="#journal">Journal</a><a href="#about">About</a></nav>
        <div class="header-actions"><button class="icon-btn search-toggle" aria-label="Search">⌕</button><button class="icon-btn" id="account-btn" aria-label="Account">♙</button><button class="bag-btn" id="cart-btn">Bag <b id="cart-count">0</b></button><button class="menu-toggle" aria-label="Menu">☰</button></div>
    </header>
    <main>
        <section class="hero" id="shop"><div class="hero-grid"></div><div class="hero-copy reveal"><p class="eyebrow">THE NEW ERA OF PERSONAL TECHNOLOGY</p><h1>Apple,<br><em>considered.</em></h1><p class="hero-sub">Curated devices. Honest condition. A better way to find your next everyday essential.</p><div class="hero-actions"><a class="btn btn-primary" href="#featured">Explore collection <span>↗</span></a><a class="text-link" href="#compare">Compare devices <span>→</span></a></div><div class="hero-meta"><span><i></i> 12-month warranty</span><span><i></i> Carbon-neutral delivery</span></div></div><div class="hero-device reveal"><div class="device-glow"></div><div class="phone"><div class="phone-camera"><i></i><i></i><i></i></div><div class="phone-screen"><span>9:41</span><strong>iPhone<br><em>16 Pro</em></strong><small>Titanium. So strong.</small></div></div><div class="float-card float-card-top"><span>01</span><b>Crafted<br>for you</b></div><div class="float-card float-card-bottom"><span class="pulse"></span><b>In stock today</b></div></div></section>
        <section class="trust-bar"><div><strong>Curated, not crowded.</strong> Every device is inspected by our team.</div><div class="trust-items"><span>⌁ <b>100+</b> quality checks</span><span>✦ <b>4.9/5</b> customer rating</span><span>↺ <b>14 days</b> easy returns</span></div></section>
        <section class="section featured" id="featured"><div class="section-head reveal"><div><p class="eyebrow">THE SHORTLIST</p><h2>Good things,<br><em>chosen well.</em></h2></div><a class="text-link" href="#all-products">View all products <span>→</span></a></div><div class="product-grid" id="product-grid"></div></section>
        <section class="categories section" id="all-products"><div class="section-head reveal"><div><p class="eyebrow">FIND YOUR FIT</p><h2>One ecosystem.<br><em>Many ways in.</em></h2></div><p class="section-note">From a first iPhone to a studio setup, discover technology that works beautifully together.</p></div><div class="category-grid"><button class="category-card category-dark reveal" data-filter="iPhone"><span class="category-no">01</span><h3>iPhone</h3><p>Powerful by design.</p><span class="category-arrow">↗</span></button><button class="category-card category-blue reveal" data-filter="Mac"><span class="category-no">02</span><h3>Mac</h3><p>Make something wonderful.</p><span class="category-arrow">↗</span></button><button class="category-card category-silver reveal" data-filter="Audio"><span class="category-no">03</span><h3>Audio</h3><p>Hear it your way.</p><span class="category-arrow">↗</span></button><button class="category-card category-gold reveal" data-filter="Watch"><span class="category-no">04</span><h3>Watch</h3><p>More than time.</p><span class="category-arrow">↗</span></button></div></section>
        <section class="manifesto section" id="about"><div class="manifesto-art"><div class="orb orb-one"></div><div class="orb orb-two"></div><div class="manifesto-card">i<span></span>Shop<small>Since 2014</small></div></div><div class="manifesto-copy reveal"><p class="eyebrow">THE ISHOP PROMISE</p><h2>Technology should<br><em>feel personal.</em></h2><p>We believe buying tech should be less transactional and more thoughtful. So we select only what we would use ourselves, check every detail, and stay with you long after checkout.</p><div class="stat-row"><div><strong data-count="10">0</strong><span>years of care</span></div><div><strong data-count="18">0</strong><span>quality checks</span></div><div><strong data-count="24">0</strong><span>hr dispatch</span></div></div><a class="text-link" href="#journal">Our story <span>→</span></a></div></section>
        <section class="compare-banner section" id="compare"><div class="compare-copy reveal"><p class="eyebrow">MAKE THE RIGHT CALL</p><h2>Side by side.<br><em>Clear as day.</em></h2><p>Not sure which iPhone is right for you? Put any two generations head to head and see what really changed.</p><button class="btn btn-light" id="open-compare">Compare iPhones <span>↗</span></button></div><div class="compare-phones"><div class="mini-phone mini-old">5s</div><div class="vs">VS</div><div class="mini-phone mini-new">16</div></div></section>
        <section class="newsletter section" id="journal"><div><p class="eyebrow">THE GOOD STUFF, OCCASIONALLY</p><h2>Stay in the loop.<br><em>Stay inspired.</em></h2></div><form id="newsletter-form"><label class="sr-only" for="email">Your email</label><input id="email" type="email" placeholder="Your email address" required><button class="btn btn-primary" type="submit">Sign me up <span>→</span></button><small>By subscribing, you agree to our very reasonable terms.</small></form></section>
    </main>
    <aside class="cart-drawer" id="cart-drawer"><div class="drawer-head"><div><p class="eyebrow">YOUR BAG</p><h2 id="bag-title">Nothing here yet.</h2></div><button class="close-btn" id="close-cart">×</button></div><div id="cart-items" class="cart-items"></div><div class="drawer-foot"><div class="subtotal"><span>Subtotal</span><strong id="cart-total">₹0</strong></div><button class="btn btn-primary checkout-btn" id="checkout-btn">Checkout <span>→</span></button><small>Shipping and taxes calculated at checkout.</small></div></aside><div class="drawer-overlay" id="drawer-overlay"></div>
    <div class="modal" id="compare-modal"><div class="modal-inner"><button class="close-btn" id="close-compare">×</button><p class="eyebrow">DEVICE COMPARISON</p><h2>Choose your <em>two.</em></h2><div class="select-row"><select id="compare-a"></select><span>vs</span><select id="compare-b"></select></div><div id="comparison-table"></div></div></div>
    <div class="toast" id="toast"></div><footer><a class="brand" href="/"><span class="brand-mark">●</span><span>iShop</span></a><span>Thoughtfully selected. Beautifully delivered.</span><span>© 2026 iShop India</span></footer>
</body>
</html>
